import './globals.css'
import type { Metadata } from 'next'
import {Providers} from "./providers";



export const metadata: Metadata = {
  title: 'Medicine Question AI',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='dark'>
      <body className="">
        <Providers>
          {children}
        </Providers>
      </body>
    </html>
  )
}
